Repository LuisMelladoDiaz/Pawtel-ComparadorDeHotelesParaMascotas, pull requests merged in 2025-04, with the labels that each got.

#257 Global filtering
  frontend/package.json
  frontend/playwright-report/index.html
  frontend/src/components/DatePicker.vue
  frontend/src/components/FilterNavBar.vue
  frontend/src/components/hotels/HotelFilters.vue
  frontend/src/components/hotels/HotelMobileFilters.vue
  frontend/src/data-layer/hooks/hotels.ts
  frontend/src/filters.ts
  frontend/src/main.ts
  frontend/src/router.ts
  frontend/src/views/Home.vue
  frontend/src/views/HotelListScreen.vue
  frontend/src/views/LayoutWithFilter.vue
Labels: Review effort 3/5

#256 Mensajes de validación
  backend/pawtel/app_users/models.py
  backend/pawtel/app_users/serializers.py
  backend/pawtel/app_users/services.py
  backend/pawtel/booking_holds/services.py
  backend/pawtel/booking_holds/views.py
  backend/pawtel/bookings/services.py
  backend/pawtel/bookings/views.py
  backend/pawtel/customers/services.py
  backend/pawtel/customers/views.py
  backend/pawtel/hotel_owners/services.py
  backend/pawtel/hotel_owners/tests/test_services2.py
  backend/pawtel/hotel_owners/views.py
  backend/pawtel/hotels/models.py
  backend/pawtel/hotels/services.py
  backend/pawtel/hotels/views.py
  backend/pawtel/room_types/services.py
  backend/pawtel/room_types/tests/test_views2.py
  backend/pawtel/room_types/views.py
  backend/pawtel/settings.py
  frontend/src/data-layer/api/bookings.ts
  frontend/src/data-layer/api/customers.ts
  frontend/src/data-layer/api/hotelOwners.ts
  frontend/src/utils/errorHandler.ts
  frontend/src/views/BookingReservationForm.vue
  frontend/src/views/EditHotel.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/MisHoteles.vue
  frontend/src/views/RegisterView.vue
  frontend/src/views/UserProfile.vue
Labels: Feature, full stack, Review effort 3/5

#243 Playwright for End2End Testing
  .github/workflows/playwright.yml
  docs/USAGE.md
  frontend/.gitignore
  frontend/package.json
  frontend/playwright.config.ts
  frontend/tests/login.spec.ts
  frontend/tests/register.spec.ts
Labels: Review effort 2/5

#254 Improve Price Range Logic
  backend/pawtel/hotels/services.py
  backend/pawtel/management/commands/seed_room_types.py
  frontend/package.json
  frontend/src/components/HotelCard.vue
  frontend/src/components/HotelDetailCard.vue
  frontend/src/components/hotels/HotelSorting.vue
  frontend/src/components/hotels/PriceRange.vue
  frontend/src/views/HotelDetailView.vue
  frontend/src/views/HotelListScreen.vue
Labels: Review effort 2/5

#265 Confirmación de Reservas
  frontend/src/components/HotelDetailCard.vue
  frontend/src/router.ts
  frontend/src/views/BookingReservationForm.vue
  frontend/src/views/HotelRoomsAndPrices.vue
Labels: Review effort 2/5

#259 Improve Hotel Management Screens
  frontend/src/components/HotelDetailCard.vue
  frontend/src/views/EditHotel.vue
  frontend/src/views/MisHoteles.vue
  frontend/src/views/UserProfile.vue
Labels: Task, frontend, Review effort 3/5

#261 Borrar booking hold activo al crear booking
  backend/pawtel/bookings/services.py
  backend/pawtel/bookings/tests/test_services.py
Labels: Feature, test, backend, Review effort 3/5

#250 Agregar admin backend
  backend/authapp/views.py
  backend/pawtel/app_admins/__init__.py
  backend/pawtel/app_admins/apps.py
  backend/pawtel/app_admins/migrations/0001_initial.py
  backend/pawtel/app_admins/migrations/__init__.py
  backend/pawtel/app_admins/models.py
  backend/pawtel/app_admins/serializers.py
  backend/pawtel/app_admins/services.py
  backend/pawtel/app_admins/tests/__init__.py
  backend/pawtel/app_admins/tests/test_models.py
  backend/pawtel/app_admins/tests/test_serializers.py
  backend/pawtel/app_admins/tests/test_services.py
  backend/pawtel/app_admins/tests/test_views.py
  backend/pawtel/app_admins/urls.py
  backend/pawtel/app_admins/views.py
  backend/pawtel/app_users/services.py
  backend/pawtel/booking_holds/tests/test_views.py
  backend/pawtel/bookings/tests/test_views.py
  backend/pawtel/customers/services.py
  backend/pawtel/customers/tests/test_views.py
  backend/pawtel/customers/views.py
  backend/pawtel/hotel_owners/services.py
  backend/pawtel/hotel_owners/tests/test_views.py
  backend/pawtel/hotel_owners/views.py
  backend/pawtel/hotels/services.py
  backend/pawtel/hotels/tests/test_views.py
  backend/pawtel/hotels/views.py
  backend/pawtel/management/commands/seed.py
  backend/pawtel/management/commands/seed_admins.py
  backend/pawtel/permission_services.py
  backend/pawtel/room_types/services.py
  backend/pawtel/room_types/tests/test_views.py
  backend/pawtel/room_types/views.py
  backend/pawtel/settings.py
  backend/pawtel/urls.py
Labels: Review effort 3/5

#267 Adicion imagenes frontend
  frontend/src/components/HotelImageUpload.vue
  frontend/src/data-layer/api/hotelImages.ts
  frontend/src/data-layer/hooks/hotelImages.ts
  frontend/src/views/EditHotel.vue
  frontend/src/views/HotelDetailView.vue
  frontend/src/views/HotelListScreen.vue
Labels: Review effort 3/5

#273 Hotfix: public routes no longer need auth and admin can still get archived
  backend/pawtel/app_admins/services.py
  backend/pawtel/customers/services.py
  backend/pawtel/customers/views.py
  backend/pawtel/hotel_owners/services.py
  backend/pawtel/hotel_owners/views.py
  backend/pawtel/hotels/services.py
  backend/pawtel/hotels/views.py
  backend/pawtel/room_types/services.py
  backend/pawtel/room_types/views.py
Labels: Review effort 2/5

#272 Asignar imágenes como portadas
  frontend/src/data-layer/api/hotelImages.ts
  frontend/src/views/EditHotel.vue
Labels: Review effort 3/5

#276 Actualización cambios en tiempo real edit hotel
  frontend/src/data-layer/hooks/hotelImages.ts
  frontend/src/data-layer/hooks/hotelOwners.ts
  frontend/src/data-layer/hooks/hotels.ts
  frontend/src/data-layer/hooks/roomTypes.ts
  frontend/src/views/EditHotel.vue
  frontend/src/views/MisHoteles.vue
Labels: Review effort 3/5

#262 Feature/user queries tan stack/246
  frontend/src/data-layer/api/customers.ts
  frontend/src/views/UserProfile.vue
Labels: Review effort 2/5

#282 Autenticar hotel owner aprobado
  backend/pawtel/booking_holds/services.py
  backend/pawtel/bookings/services.py
  backend/pawtel/hotel_owners/services.py
  backend/pawtel/hotel_owners/tests/test_views.py
  backend/pawtel/hotel_owners/views.py
  backend/pawtel/hotels/services.py
  backend/pawtel/hotels/tests/test_views.py
  backend/pawtel/hotels/tests/test_views2.py
  backend/pawtel/hotels/tests/test_views3.py
  backend/pawtel/management/commands/seed_hotel_owners.py
  backend/pawtel/room_types/services.py
  backend/pawtel/room_types/tests/test_views.py
  backend/pawtel/room_types/tests/test_views2.py
  backend/pawtel/room_types/tests/test_views3.py
Labels: Review effort 2/5

#280 Crear rutas hotel owner pendientes aprobación y rechazar aprobación
  backend/pawtel/hotel_owners/services.py
  backend/pawtel/hotel_owners/tests/test_services.py
  backend/pawtel/hotel_owners/tests/test_views.py
  backend/pawtel/hotel_owners/views.py
  backend/pawtel/permission_services.py
Labels: Feature, backend, Review effort 2/5

#283 Trabajos automatizados backend
  backend/celerybeat-schedule.bak
  backend/celerybeat-schedule.dat
  backend/celerybeat-schedule.dir
  backend/pawtel/__init__.py
  backend/pawtel/booking_holds/tasks.py
  backend/pawtel/bookings/tasks.py
  backend/pawtel/celery.py
  backend/pawtel/customers/tasks.py
  backend/pawtel/hotel_owners/tasks.py
  backend/pawtel/hotels/tasks.py
  backend/pawtel/room_types/tasks.py
  backend/pawtel/settings.py
  backend/requirements.txt
Labels: Feature, backend, Review effort 3/5

#286 Feature: Mejoras de pantallas Home, Sobre Nosotros, Contact, Dueños de Alojamientos
  frontend/src/assets/app-promo.gif
  frontend/src/assets/bienestar_icon.png
  frontend/src/assets/calendar_icon.png
  frontend/src/assets/confort_icon.png
  frontend/src/assets/contact.jpg
  frontend/src/assets/email_icon.png
  frontend/src/assets/europa_icon.png
  frontend/src/assets/hotelOwners_portada.jpg
  frontend/src/assets/hotel_icon.png
  frontend/src/assets/imgdc.webp
  frontend/src/assets/insta_icon.png
  frontend/src/assets/paso1.avif
  frontend/src/assets/paso1.jpg
  frontend/src/assets/paso2.jpg
  frontend/src/assets/paso2M.jpg
  frontend/src/assets/paso3.avif
  frontend/src/assets/paso3.jpg
  frontend/src/assets/pawtel_img.png
  frontend/src/assets/pets_icon.png
  frontend/src/assets/pmBackend.jpg
  frontend/src/assets/pmFrontend.jpg
  frontend/src/assets/pmFullstack.jpg
  frontend/src/assets/pmOne.jpg
  frontend/src/assets/pmTwo.jpg
  frontend/src/assets/reservas_icon.png
  frontend/src/assets/security_icon.png
  frontend/src/assets/step1.jpg
  frontend/src/assets/step2.jpg
  frontend/src/assets/step3.jpg
  frontend/src/assets/stepOne.png
  frontend/src/assets/stepThree.png
  frontend/src/assets/stepTwo.png
  frontend/src/assets/stepTwo_.png
  frontend/src/assets/tiktok_icon.png
  frontend/src/assets/warning_icon.png
  frontend/src/assets/x_icon.png
  frontend/src/components/AnimatedCounters.vue
  frontend/src/components/FaqAccordion.vue
  frontend/src/components/Footer.vue
  frontend/src/main.ts
  frontend/src/router.ts
  frontend/src/views/AboutUs.vue
  frontend/src/views/Contact.vue
  frontend/src/views/Home.vue
  frontend/src/views/HotelOwners.vue
Labels: style, frontend, Review effort 3/5

#278 Añadir Reservas a Gestión de Hotel
  backend/pawtel/app_users/migrations/0003_alter_appuser_phone.py
  backend/pawtel/app_users/models.py
  backend/pawtel/customers/services.py
  backend/pawtel/hotels/migrations/0003_alter_hotel_name.py
  backend/pawtel/hotels/services.py
  backend/pawtel/permission_services.py
  frontend/src/components/HotelBookings.vue
  frontend/src/components/HotelCard.vue
  frontend/src/components/hotels/HotelList.vue
  frontend/src/data-layer/api/bookings.ts
  frontend/src/data-layer/api/customers.ts
  frontend/src/data-layer/api/hotelOwners.ts
  frontend/src/data-layer/api/hotels.ts
  frontend/src/data-layer/api/roomTypes.ts
  frontend/src/data-layer/auth.ts
  frontend/src/data-layer/hooks/customers.ts
  frontend/src/data-layer/hooks/hotelOwners.ts
  frontend/src/data-layer/hooks/hotels.ts
  frontend/src/data-layer/hooks/roomTypes.ts
  frontend/src/views/EditHotel.vue
  frontend/src/views/MisHoteles.vue
  frontend/src/views/MyBookings.vue
  frontend/src/views/UserProfile.vue
Labels: Feature, frontend, Review effort 2/5

#285 Restablecimiento de contraseña
  backend/.env.example
  backend/authapp/urls.py
  backend/authapp/views.py
  backend/pawtel/app_users/migrations/0003_alter_appuser_phone.py
  backend/pawtel/hotels/migrations/0003_alter_hotel_name.py
  backend/pawtel/settings.py
  frontend/src/components/NavBarTerracotaLogoOnly.vue
  frontend/src/data-layer/auth.ts
  frontend/src/router.ts
  frontend/src/views/EmailPasswordReset.vue
  frontend/src/views/LayoutLogoNavBarOnly.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/ResetPassword.vue
Labels: full stack, Review effort 3/5

#288 Cambiar seeder para tener imagenes reales
  backend/pawtel/images_hotel/descarga.jpg
  backend/pawtel/images_hotel/detalles1.jpg
  backend/pawtel/images_hotel/detalles2.jpg
  backend/pawtel/images_hotel/detalles3.jpg
  backend/pawtel/images_hotel/detalles4.jpg
  backend/pawtel/images_hotel/foto1.jpg
  backend/pawtel/images_hotel/foto2.jpg
  backend/pawtel/images_hotel/hotel1.jpg
  backend/pawtel/images_hotel/hotel2.jpg
  backend/pawtel/images_hotel/hotel3.jpg
  backend/pawtel/images_hotel/hotel4.jpg
  backend/pawtel/images_hotel/hotel5.jpg
  backend/pawtel/images_hotel/hotel6.jpg
  backend/pawtel/images_hotel/images (1).jpg
  backend/pawtel/images_hotel/images (2).jpg
  backend/pawtel/images_hotel/images (3).jpg
  backend/pawtel/images_hotel/images (4).jpg
  backend/pawtel/images_hotel/images (5).jpg
  backend/pawtel/images_hotel/images (6).jpg
  backend/pawtel/images_hotel/images.jpg
  backend/pawtel/management/commands/seed_hotel_images.py
Labels: Review effort 2/5

#289 End2End Test
  docs/Sprint_3/PMBOK/seguimiento_y_control/usuarios_piloto/Informe de feedback_sesion_2.pdf
  frontend/tests/book_flow.spec.ts
  frontend/tests/customer_book.spec.ts
  frontend/tests/filter.spec.ts
  frontend/tests/home.spec.ts
  frontend/tests/hotel_actions.spec.ts
Labels: test, Review effort 2/5

#295 Migrate from axios
  frontend/package.json
  frontend/src/api.ts
  frontend/src/axios-setup.ts
  frontend/src/data-layer/api/bookingholds.ts
  frontend/src/data-layer/api/bookings.ts
  frontend/src/data-layer/api/customers.ts
  frontend/src/data-layer/api/hotelImages.ts
  frontend/src/data-layer/api/hotelOwners.ts
  frontend/src/data-layer/api/hotels.ts
  frontend/src/data-layer/api/roomTypes.ts
  frontend/src/data-layer/auth.ts
  frontend/src/data-layer/hooks/customers.ts
  frontend/src/data-layer/hooks/hotelOwners.ts
  frontend/src/data-layer/hooks/hotels.ts
  frontend/src/data-layer/hotelService.ts
  frontend/src/data-layer/pets.ts
  frontend/src/main.ts
  frontend/src/router.ts
  frontend/src/utils/errorHandler.ts
  frontend/src/views/EditHotel.vue
  frontend/src/views/MisHoteles.vue
Labels: Review effort 3/5
