Repository LuisMelladoDiaz/Pawtel-ComparadorDeHotelesParaMascotas, pull requests merged in 2025-03, with the labels that each got.

#79 Creación modelos y serializadores. #61
  backend/pawtel/appUsers/__init__.py
  backend/pawtel/appUsers/apps.py
  backend/pawtel/appUsers/migrations/0001_initial.py
  backend/pawtel/appUsers/migrations/__init__.py
  backend/pawtel/appUsers/models.py
  backend/pawtel/appUsers/serializers.py
  backend/pawtel/appUsers/tests/__init__.py
  backend/pawtel/appUsers/tests/test_models.py
  backend/pawtel/hotelOwners/__init__.py
  backend/pawtel/hotelOwners/apps.py
  backend/pawtel/hotelOwners/migrations/0001_initial.py
  backend/pawtel/hotelOwners/migrations/__init__.py
  backend/pawtel/hotelOwners/models.py
  backend/pawtel/hotelOwners/serializers.py
  backend/pawtel/hotelOwners/tests/__init__.py
  backend/pawtel/hotelOwners/tests/test_models.py
  backend/pawtel/hotels/__init__.py
  backend/pawtel/hotels/apps.py
  backend/pawtel/hotels/migrations/0001_initial.py
  backend/pawtel/hotels/migrations/__init__.py
  backend/pawtel/hotels/models.py
  backend/pawtel/hotels/serializers.py
  backend/pawtel/hotels/tests/__init__.py
  backend/pawtel/hotels/tests/test_models.py
  backend/pawtel/roomTypes/__init__.py
  backend/pawtel/roomTypes/apps.py
  backend/pawtel/roomTypes/migrations/0001_initial.py
  backend/pawtel/roomTypes/migrations/__init__.py
  backend/pawtel/roomTypes/models.py
  backend/pawtel/roomTypes/serializers.py
  backend/pawtel/roomTypes/tests/__init__.py
  backend/pawtel/roomTypes/tests/test_models.py
  backend/pawtel/rooms/__init__.py
  backend/pawtel/rooms/apps.py
  backend/pawtel/rooms/migrations/0001_initial.py
  backend/pawtel/rooms/migrations/__init__.py
  backend/pawtel/rooms/models.py
  backend/pawtel/rooms/serializers.py
  backend/pawtel/rooms/tests/__init__.py
  backend/pawtel/rooms/tests/test_models.py
  backend/pawtel/settings.py
Labels: Review effort 4/5, backend

#88 Fix en los imports de los componentes en Frontend
  frontend/src/views/Componentes1.vue
  frontend/src/views/DevelopmentScreen.vue
  frontend/src/views/TemplateScreen1.vue
  frontend/src/views/TemplateScreen2.vue
Labels: Review effort 2/5

#89 Add @ alias on frontend
  frontend/package-lock.json
  frontend/package.json
  frontend/tsconfig.app.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
Labels: Review effort 1/5

#85 Autenticación básica. #45
  .gitignore
  .vscode/launch.json
  backend/authapp/__init__.py
  backend/authapp/admin.py
  backend/authapp/apps.py
  backend/authapp/management/commands/create_test_users.py
  backend/authapp/migrations/__init__.py
  backend/authapp/models.py
  backend/authapp/tests.py
  backend/authapp/urls.py
  backend/authapp/views.py
  backend/pawtel/settings.py
  backend/pawtel/urls.py
  backend/requirements.txt
  frontend/src/axios-setup.ts
  frontend/src/components/Alert.vue
  frontend/src/components/DatePicker.vue
  frontend/src/components/DropdownPicker.vue
  frontend/src/components/HotelCard.vue
  frontend/src/components/InputNumber.vue
  frontend/src/components/InputText.vue
  frontend/src/components/LoadingSpinner.vue
  frontend/src/components/LogoutButton.vue
  frontend/src/components/NavBar.vue
  frontend/src/components/NavBarTerracota.vue
  frontend/src/data-layer/auth.ts
  frontend/src/main.ts
  frontend/src/router.ts
  frontend/src/style.css
  frontend/src/views/Componentes1.vue
  frontend/src/views/Componentes2.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/TemplateScreen1.vue
  frontend/src/views/TemplateScreen2.vue
Labels: Feature, Review effort 3/5

#92 Pantalla de listado de hoteles
  frontend/src/components/AppliedFilter.vue
  frontend/src/components/HotelCard.vue
  frontend/src/router.ts
  frontend/src/views/Componentes2.vue
  frontend/src/views/DevelopmentScreen.vue
  frontend/src/views/HotelListScreen.vue
Labels: Review effort 4/5, Feature, frontend

#93 TanStack queries of Hotels and HotelOwners
  frontend/src/data-layer/api/hotelOwners.ts
  frontend/src/data-layer/api/hotels.ts
  frontend/src/data-layer/hooks/hotelOwners.ts
  frontend/src/data-layer/hooks/hotels.ts
Labels: full stack, Review effort 3/5

#94 Hotel Owner Screen
  frontend/src/components/Button.vue
  frontend/src/components/HotelCard.vue
  frontend/src/components/NavBar.vue
  frontend/src/components/NavBarTerracota.vue
  frontend/src/router.ts
  frontend/src/views/DevelopmentScreen.vue
  frontend/src/views/HotelListScreen.vue
  frontend/src/views/HotelOwnerPanel.vue
  frontend/src/views/TemplateScreen1.vue
  frontend/src/views/TemplateScreen2.vue
Labels: Review effort 3/5

#90 Implemented profile screen
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Modal.vue
  frontend/src/components/NavBar.vue
  frontend/src/components/NavBarTerracota.vue
  frontend/src/router.ts
  frontend/src/views/DevelopmentScreen.vue
  frontend/src/views/UserProfile.vue
Labels: Review effort 2/5

#84 Implemented hotels' details screen. #59
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/foto1.jpg
  frontend/src/assets/foto2.jpg
  frontend/src/components/HotelCard.vue
  frontend/src/components/HotelDetailCard.vue
  frontend/src/data-layer/hotelService.ts
  frontend/src/main.ts
  frontend/src/router.ts
  frontend/src/views/HomeView.vue
  frontend/src/views/HotelDetailView.vue
  frontend/src/views/HotelListView.vue
Labels: Feature, frontend, Review effort 2/5

#82 Implemented PWA structure
  README.md
  docs/USAGE.md
  frontend/.gitignore
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/apple-touch-icon.png
  frontend/public/favicon-16x16.png
  frontend/public/favicon-32x32.png
  frontend/public/favicon.ico
  frontend/public/pwa-192x192.png
  frontend/public/pwa-512x512.png
  frontend/public/pwa-maskable-192x192.png
  frontend/public/pwa-maskable-512x512.png
  frontend/vite.config.ts
Labels: Review effort 2/5

#96 Implemented Screens for Login and Register
  frontend/src/data-layer/api/hotelOwners.ts
  frontend/src/data-layer/api/hotels.ts
  frontend/src/router.ts
  frontend/src/views/LoginView.vue
  frontend/src/views/RegisterView.vue
Labels: frontend, Review effort 3/5

#100 Register hotel owner
  backend/authapp/urls.py
  backend/authapp/views.py
  backend/pawtel/app_users/migrations/0001_initial.py
  backend/pawtel/app_users/models.py
  backend/pawtel/hotel_owners/migrations/0001_initial.py
  backend/pawtel/hotel_owners/models.py
  backend/pawtel/hotels/migrations/0001_initial.py
  backend/pawtel/hotels/migrations/__init__.py
  backend/pawtel/room_types/migrations/0001_initial.py
  backend/pawtel/room_types/migrations/0002_alter_roomtype_pet_type.py
  backend/pawtel/room_types/migrations/__init__.py
  backend/pawtel/rooms/migrations/0001_initial.py
  backend/pawtel/rooms/migrations/__init__.py
  backend/pawtel/settings.py
  frontend/package-lock.json
  frontend/src/components/NavBar.vue
  frontend/src/data-layer/api/hotelOwners.ts
  frontend/src/views/LoginView.vue
  frontend/src/views/RegisterView.vue
  package-lock.json
Labels: Review effort 3/5

#99 Crear servicios y controladores hotel y hotel owner
  backend/authapp/views.py
  backend/pawtel/app_users/models.py
  backend/pawtel/app_users/serializers.py
  backend/pawtel/app_users/services.py
  backend/pawtel/app_users/tests/test_models.py
  backend/pawtel/app_users/tests/test_serializers.py
  backend/pawtel/app_users/tests/test_services.py
  backend/pawtel/hotel_owners/models.py
  backend/pawtel/hotel_owners/serializers.py
  backend/pawtel/hotel_owners/services.py
  backend/pawtel/hotel_owners/tests/test_models.py
  backend/pawtel/hotel_owners/tests/test_serializers.py
  backend/pawtel/hotel_owners/tests/test_services.py
  backend/pawtel/hotel_owners/tests/test_views.py
  backend/pawtel/hotel_owners/urls.py
  backend/pawtel/hotel_owners/views.py
  backend/pawtel/hotels/migrations/0001_initial.py
  backend/pawtel/hotels/migrations/__init__.py
  backend/pawtel/hotels/services.py
  backend/pawtel/hotels/tests/test_models.py
  backend/pawtel/hotels/tests/test_serializers.py
  backend/pawtel/hotels/tests/test_services.py
  backend/pawtel/hotels/tests/test_views.py
  backend/pawtel/hotels/urls.py
  backend/pawtel/hotels/views.py
  backend/pawtel/room_types/migrations/0001_initial.py
  backend/pawtel/room_types/migrations/__init__.py
  backend/pawtel/room_types/tests/test_models.py
  backend/pawtel/room_types/tests/test_serializers.py
  backend/pawtel/rooms/migrations/0001_initial.py
  backend/pawtel/rooms/migrations/__init__.py
  backend/pawtel/rooms/tests/test_models.py
  backend/pawtel/rooms/tests/test_serializers.py
  backend/pawtel/urls.py
Labels: Review effort 3/5

#101 Crear servicios y controladores room type y room
  backend/pawtel/app_users/services.py
  backend/pawtel/hotel_owners/models.py
  backend/pawtel/hotel_owners/services.py
  backend/pawtel/hotel_owners/tests/test_views.py
  backend/pawtel/hotels/services.py
  backend/pawtel/hotels/views.py
  backend/pawtel/room_types/services.py
  backend/pawtel/room_types/tests/test_services.py
  backend/pawtel/room_types/tests/test_views.py
  backend/pawtel/room_types/urls.py
  backend/pawtel/room_types/views.py
  backend/pawtel/rooms/services.py
  backend/pawtel/rooms/tests/test_views.py
  backend/pawtel/rooms/urls.py
  backend/pawtel/rooms/views.py
  backend/pawtel/urls.py
Labels: Feature, test, backend, Review effort 2/5

#103 Pulir contributing file
  docs/CONTRIBUTING.md
Labels: documentation, Review effort 2/5

#105 Creacion KBReport
  docs/Sprint_1/KBreport.md
  docs/Sprint_1/KBreport_dummy.md
  docs/Sprint_1/feedback_semanal/2025_02_21-Semana3.md
  docs/Sprint_1/feedback_semanal/2025_03_07-Semana5.md
Labels: documentation, Review effort 2/5

#113 Crear pantallas Sobre Nosotros y Contacto
  frontend/src/components/NavBar.vue
  frontend/src/components/NavBarTerracota.vue
  frontend/src/router.ts
  frontend/src/views/AboutUs.vue
  frontend/src/views/Contact.vue
Labels: Feature, frontend, Review effort 2/5

#114 Conectar Backend y Frontend
  backend/pawtel/settings.py
  backend/sample/management/commands/create_room_types.py
  backend/sample/management/commands/create_test_hotels.py
  frontend/src/components/HotelCard.vue
  frontend/src/components/HotelDetailCard.vue
  frontend/src/components/NavBar.vue
  frontend/src/components/NavBarTerracota.vue
  frontend/src/router.ts
  frontend/src/views/Home.vue
  frontend/src/views/HotelDetailView.vue
  frontend/src/views/HotelListScreen.vue
  frontend/src/views/HotelListView.vue
  frontend/src/views/HotelOwnerPanel.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/RegisterView.vue
Labels: Feature, frontend, full stack, Review effort 3/5

#119 Implement backend-frontend connection things
  backend/pawtel/hotel_owners/services.py
  backend/pawtel/hotel_owners/views.py
  backend/pawtel/hotels/services.py
  backend/pawtel/management/commands/seed_hotel_owners.py
  frontend/src/axios-setup.ts
  frontend/src/components/HotelCard.vue
  frontend/src/data-layer/api/hotelOwners.ts
  frontend/src/data-layer/api/hotels.ts
  frontend/src/data-layer/hooks/hotelOwners.ts
  frontend/src/data-layer/hooks/hotels.ts
  frontend/src/main.ts
  frontend/src/views/HotelListScreen.vue
  frontend/src/views/HotelOwnerPanel.vue
  frontend/src/views/LoginView.vue
Labels: Review effort 3/5

#123 Auth improvements
  backend/authapp/urls.py
  backend/authapp/views.py
  backend/pawtel/app_users/serializers.py
  backend/pawtel/hotel_owners/tests/test_services.py
  backend/pawtel/hotel_owners/tests/test_views.py
  backend/pawtel/settings.py
  backend/pawtel/urls.py
  frontend/src/axios-setup.ts
  frontend/src/components/NavBar.vue
  frontend/src/components/NavBarTerracota.vue
  frontend/src/data-layer/auth.ts
  frontend/src/main.ts
Labels: Review effort 3/5

#128 Seeders y Población
  backend/pawtel/management/commands/seed_hotel_owners.py
  backend/pawtel/management/commands/seed_hotels.py
  backend/pawtel/management/commands/seed_room_types.py
  backend/pawtel/management/commands/seed_rooms.py
Labels: database, backend, Review effort 2/5

#124 Elminación y Edición de hoteles
  backend/pawtel/hotels/services.py
  frontend/src/components/NavBar.vue
  frontend/src/components/NavBarTerracota.vue
  frontend/src/data-layer/api/hotels.ts
  frontend/src/views/HotelOwnerPanel.vue
Labels: frontend, Review effort 2/5

#133 Ocultar botón de Iniciar sesión para usuario autenticado.
  frontend/src/views/Home.vue
Labels: Review effort 1/5

#127 Add error messages in frontend
  frontend/package.json
  frontend/src/main.ts
  frontend/src/views/LoginView.vue
  frontend/src/views/RegisterView.vue
Labels: Review effort 2/5

#134 Pulir filtrado
  backend/pawtel/hotels/services.py
  backend/pawtel/management/commands/seed_hotels.py
  frontend/src/components/HotelCard.vue
  frontend/src/data-layer/hooks/hotels.ts
  frontend/src/views/Home.vue
  frontend/src/views/HotelListScreen.vue
Labels: full stack, Review effort 3/5

#135 Implementación botones register y login ver y ocultar contraseña
  frontend/src/views/LoginView.vue
  frontend/src/views/RegisterView.vue
Labels: Review effort 2/5

#136 Fix authorization in creation.
  backend/pawtel/hotel_owners/models.py
  backend/pawtel/hotel_owners/serializers.py
  backend/pawtel/hotel_owners/services.py
  backend/pawtel/hotels/services.py
  backend/pawtel/hotels/views.py
  backend/pawtel/room_types/services.py
  backend/pawtel/room_types/views.py
  backend/pawtel/rooms/services.py
  backend/pawtel/rooms/views.py
Labels: Review effort 2/5

#138 Mensajes crud de hoteles
  frontend/src/views/HotelListScreen.vue
  frontend/src/views/HotelOwnerPanel.vue
Labels: Review effort 2/5

#140 Modificar la portada de los archivos .md issue #139
  docs/Sprint_1/AIusage.md
  docs/Sprint_1/KBreport.md
  docs/Sprint_1/PMBOK/seguimiento_y_control/Informe_de_desempeño-Sprint_1-Backend.md
  docs/Sprint_1/actas_de_reunión/2025_02_22-Inicio_Sprint1.md
  docs/Sprint_1/actas_de_reunión/2025_03_03-Seguimiento_Sprint1.md
  docs/Sprint_1/actas_de_reunión/2025_03_06-Seguimiento_Backend.md
  docs/Sprint_1/actas_de_reunión/2025_03_09-Control_Sprint1
  docs/Sprint_1/commitmentAgreement.md
  docs/Sprint_1/feedback_semanal/2025_02_21-Semana3.md
  docs/Sprint_1/feedback_semanal/2025_03_07-Feedback_semana_6.md
  docs/Sprint_1/feedback_semanal/2025_03_07-Semana5.md
  docs/Sprint_1/performanceEvaluation.md
  docs/Sprint_1/pilotUsers.md
  docs/Sprint_1/pilotUsersCommitmentAgreement.md
  docs/Sprint_1/pilotUsersPerformanceEvaluation.md
  frontend/src/assets/pawtel.jpg
Labels: documentation, Task, style, Review effort 2/5

#131 Adaptar componentes y pantallas
  backend/pawtel/hotels/migrations/0001_initial.py
  backend/pawtel/hotels/models.py
  backend/pawtel/hotels/serializers.py
  backend/pawtel/hotels/services.py
  backend/pawtel/management/commands/seed_hotels.py
  frontend/src/assets/hotel.jpg
  frontend/src/assets/hoteles/detalles1.jpg
  frontend/src/assets/hoteles/detalles2.jpg
  frontend/src/assets/hoteles/detalles3.jpg
  frontend/src/assets/hoteles/detalles4.jpg
  frontend/src/assets/hoteles/foto1.jpg
  frontend/src/assets/hoteles/foto2.jpg
  frontend/src/assets/hoteles/hotel1.jpg
  frontend/src/assets/hoteles/hotel2.jpg
  frontend/src/assets/hoteles/hotel3.jpg
  frontend/src/assets/hoteles/hotel4.jpg
  frontend/src/assets/hoteles/hotel5.jpg
  frontend/src/assets/hoteles/hotel6.jpg
  frontend/src/components/FilterNavBar.vue
  frontend/src/components/HotelCard.vue
  frontend/src/components/HotelDetailCard.vue
  frontend/src/components/NavBar.vue
  frontend/src/components/NavBarTerracota.vue
  frontend/src/tailwindcss
  frontend/src/views/HotelDetailView.vue
  frontend/src/views/HotelListScreen.vue
Labels: Feature, frontend, Review effort 3/5

#145 Documentación automática API
  backend/pawtel/settings.py
  backend/pawtel/urls.py
  backend/requirements.txt
  backend/sample/__init__.py
  backend/sample/admin.py
  backend/sample/apps.py
  backend/sample/management/commands/create_room_types.py
  backend/sample/management/commands/create_test_hotels.py
  backend/sample/migrations/__init__.py
  backend/sample/models.py
  backend/sample/tests.py
  backend/sample/urls.py
  backend/sample/views.py
Labels: Review effort 2/5

#155 Register por rol
  backend/authapp/views.py
  backend/pawtel/customers/__init__.py
  backend/pawtel/customers/apps.py
  backend/pawtel/customers/migrations/0001_initial.py
  backend/pawtel/customers/migrations/__init__.py
  backend/pawtel/customers/models.py
  backend/pawtel/customers/serializers.py
  backend/pawtel/customers/services.py
  backend/pawtel/customers/tests/__init__.py
  backend/pawtel/customers/tests/test_models.py
  backend/pawtel/customers/tests/test_serializers.py
  backend/pawtel/customers/tests/test_services.py
  backend/pawtel/customers/tests/test_views.py
  backend/pawtel/customers/urls.py
  backend/pawtel/customers/views.py
  backend/pawtel/hotels/serializers.py
  backend/pawtel/management/commands/seed.py
  backend/pawtel/management/commands/seed_customers.py
  backend/pawtel/management/commands/seed_hotels.py
  backend/pawtel/settings.py
  backend/pawtel/urls.py
  frontend/src/data-layer/api/customers.ts
  frontend/src/data-layer/hooks/customers.ts
  frontend/src/views/RegisterView.vue
Labels: Review effort 4/5, Feature, full stack

#153 Refactorizar pks en rutas
  backend/pawtel/hotel_owners/services.py
  backend/pawtel/hotel_owners/tests/test_views.py
  backend/pawtel/hotel_owners/views.py
  frontend/src/data-layer/api/hotelOwners.ts
Labels: Review effort 2/5

#160 Eliminar Room e incorporarlo en RoomType
  backend/pawtel/hotels/services.py
  backend/pawtel/hotels/tests/test_services.py
  backend/pawtel/hotels/tests/test_views.py
  backend/pawtel/hotels/views.py
  backend/pawtel/management/commands/seed.py
  backend/pawtel/management/commands/seed_room_types.py
  backend/pawtel/management/commands/seed_rooms.py
  backend/pawtel/room_types/migrations/0002_roomtype_num_rooms_alter_roomtype_capacity.py
  backend/pawtel/room_types/models.py
  backend/pawtel/room_types/serializers.py
  backend/pawtel/room_types/services.py
  backend/pawtel/room_types/tests/test_models.py
  backend/pawtel/room_types/tests/test_serializers.py
  backend/pawtel/room_types/tests/test_services.py
  backend/pawtel/room_types/tests/test_views.py
  backend/pawtel/room_types/views.py
  backend/pawtel/rooms/__init__.py
  backend/pawtel/rooms/apps.py
  backend/pawtel/rooms/migrations/0001_initial.py
  backend/pawtel/rooms/migrations/__init__.py
  backend/pawtel/rooms/models.py
  backend/pawtel/rooms/serializers.py
  backend/pawtel/rooms/services.py
  backend/pawtel/rooms/tests/__init__.py
  backend/pawtel/rooms/tests/test_models.py
  backend/pawtel/rooms/tests/test_serializers.py
  backend/pawtel/rooms/tests/test_views.py
  backend/pawtel/rooms/urls.py
  backend/pawtel/rooms/views.py
  backend/pawtel/settings.py
  backend/pawtel/urls.py
Labels: Review effort 3/5

#162 Crear modelo,serializadores,servicios y controladores de bookings
  backend/pawtel/bookings/__init__.py
  backend/pawtel/bookings/apps.py
  backend/pawtel/bookings/migrations/0001_initial.py
  backend/pawtel/bookings/migrations/__init__.py
  backend/pawtel/bookings/models.py
  backend/pawtel/bookings/serializers.py
  backend/pawtel/bookings/services.py
  backend/pawtel/bookings/tests/__init__.py
  backend/pawtel/bookings/tests/test_models.py
  backend/pawtel/bookings/tests/test_serializers.py
  backend/pawtel/bookings/tests/test_services.py
  backend/pawtel/bookings/tests/test_views.py
  backend/pawtel/bookings/urls.py
  backend/pawtel/bookings/views.py
  backend/pawtel/settings.py
  backend/pawtel/urls.py
Labels: Review effort 3/5

#165 Refactor Backend: Improved Imports and Enhanced Role Access for AppUser
  backend/authapp/tests.py
  backend/authapp/tests/__init__.py
  backend/authapp/tests/test_views.py
  backend/authapp/views.py
  backend/pawtel/app_users/services.py
  backend/pawtel/customers/migrations/0002_alter_customer_user.py
  backend/pawtel/customers/models.py
  backend/pawtel/hotel_owners/migrations/0002_alter_hotelowner_user.py
  backend/pawtel/hotel_owners/models.py
  backend/pawtel/hotels/services.py
  backend/pawtel/room_types/services.py
Labels: Task, refactor, test, backend, Review effort 2/5

#177 Booking hold without room type availability
  backend/pawtel/booking_holds/__init__.py
  backend/pawtel/booking_holds/apps.py
  backend/pawtel/booking_holds/migrations/0001_initial.py
  backend/pawtel/booking_holds/migrations/__init__.py
  backend/pawtel/booking_holds/models.py
  backend/pawtel/booking_holds/serializers.py
  backend/pawtel/booking_holds/services.py
  backend/pawtel/booking_holds/tests/__init__.py
  backend/pawtel/booking_holds/tests/test_models.py
  backend/pawtel/booking_holds/tests/test_serializers.py
  backend/pawtel/booking_holds/tests/test_services.py
  backend/pawtel/booking_holds/tests/test_views.py
  backend/pawtel/booking_holds/urls.py
  backend/pawtel/booking_holds/views.py
  backend/pawtel/management/commands/seed.py
  backend/pawtel/management/commands/seed_booking_holds.py
  backend/pawtel/settings.py
  backend/pawtel/urls.py
Labels: Review effort 3/5

#175 Comprobar disponibilidad room types
  backend/pawtel/app_users/services.py
  backend/pawtel/bookings/models.py
  backend/pawtel/bookings/services.py
  backend/pawtel/customers/services.py
  backend/pawtel/hotel_owners/services.py
  backend/pawtel/hotels/services.py
  backend/pawtel/room_types/services.py
  backend/pawtel/room_types/tests/test_services.py
  backend/pawtel/room_types/tests/test_views2.py
  backend/pawtel/room_types/views.py
Labels: Feature, backend, Review effort 2/5

#169 Crear metodos para obtener bookings por customer y por hotel.
  backend/pawtel/bookings/tests/test_services.py
  backend/pawtel/bookings/tests/test_views.py
  backend/pawtel/customers/services.py
  backend/pawtel/customers/tests/test_services2.py
  backend/pawtel/customers/tests/test_views2.py
  backend/pawtel/customers/views.py
  backend/pawtel/hotels/services.py
  backend/pawtel/hotels/tests/test_services2.py
  backend/pawtel/hotels/tests/test_views2.py
  backend/pawtel/hotels/views.py
Labels: Feature, backend, Review effort 2/5

#178 Restricciones hotel image test y seeders
  backend/pawtel/hotels/services.py
  backend/pawtel/hotels/tests/test_views.py
  backend/pawtel/hotels/urls.py
  backend/pawtel/hotels/views.py
  backend/pawtel/management/commands/seed.py
  backend/pawtel/management/commands/seed_hotel_images.py
Labels: Feature, test, backend, Review effort 3/5

#179 Validacion de formularios con vee validate
  .gitignore
  frontend/package.json
  frontend/src/main.ts
  frontend/src/validation-messages.ts
  frontend/src/views/HotelOwnerPanel.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/RegisterView.vue
Labels: Review effort 3/5

#166 Reestablecimiento de contraseña
  backend/.env.example
  backend/authapp/urls.py
  backend/authapp/views.py
  backend/pawtel/settings.py
  frontend/src/components/NavBarTerracotaLogoOnly.vue
  frontend/src/data-layer/auth.ts
  frontend/src/router.ts
  frontend/src/views/EmailPasswordReset.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/ResetPassword.vue
Labels: Feature, full stack, Review effort 2/5

#163 Añadir filtros en la URL
  frontend/package.json
  frontend/src/views/HotelListScreen.vue
Labels: Task, frontend, Review effort 2/5

#184 Get Hotel from RoomType ID
  backend/pawtel/app_users/services.py
  backend/pawtel/customers/views.py
  backend/pawtel/room_types/services.py
  backend/pawtel/room_types/tests/test_views.py
  backend/pawtel/room_types/views.py
Labels: Review effort 2/5

#186 Finishing booking hold
  backend/pawtel/booking_holds/migrations/0001_initial.py
  backend/pawtel/booking_holds/models.py
  backend/pawtel/booking_holds/services.py
  backend/pawtel/booking_holds/tests/test_models.py
  backend/pawtel/booking_holds/tests/test_views.py
  backend/pawtel/bookings/services.py
  backend/pawtel/room_types/services.py
Labels: Review effort 2/5

#190 Refactorizar autorización y roles
  backend/pawtel/app_users/models.py
  backend/pawtel/app_users/services.py
  backend/pawtel/booking_holds/services.py
  backend/pawtel/booking_holds/tests/test_services.py
  backend/pawtel/booking_holds/tests/test_views.py
  backend/pawtel/booking_holds/views.py
  backend/pawtel/bookings/services.py
  backend/pawtel/bookings/views.py
  backend/pawtel/customers/services.py
  backend/pawtel/customers/tests/test_services2.py
  backend/pawtel/customers/tests/test_views2.py
  backend/pawtel/customers/views.py
  backend/pawtel/hotel_owners/services.py
  backend/pawtel/hotel_owners/tests/test_services.py
  backend/pawtel/hotel_owners/tests/test_views.py
  backend/pawtel/hotel_owners/views.py
  backend/pawtel/hotels/services.py
  backend/pawtel/hotels/tests/test_services.py
  backend/pawtel/hotels/tests/test_services2.py
  backend/pawtel/hotels/tests/test_views.py
  backend/pawtel/hotels/tests/test_views2.py
  backend/pawtel/hotels/views.py
  backend/pawtel/room_types/services.py
Labels: Review effort 4/5

#195 Fix booking_hold
  backend/pawtel/management/commands/seed_booking_holds.py
Labels: Review effort 1/5

#194 Refactorizar autorización y roles
  backend/authapp/views.py
  backend/pawtel/app_users/models.py
  backend/pawtel/app_users/services.py
  backend/pawtel/booking_holds/services.py
  backend/pawtel/booking_holds/views.py
  backend/pawtel/bookings/services.py
  backend/pawtel/bookings/views.py
  backend/pawtel/customers/services.py
  backend/pawtel/customers/views.py
  backend/pawtel/hotel_owners/services.py
  backend/pawtel/hotel_owners/views.py
  backend/pawtel/hotels/services.py
  backend/pawtel/hotels/tests/test_views.py
  backend/pawtel/hotels/views.py
  backend/pawtel/permission_services.py
  backend/pawtel/room_types/services.py
  backend/pawtel/room_types/views.py
Labels: Review effort 3/5

#201 Borrar pantallas en desuso
  frontend/src/router.ts
  frontend/src/views/Componentes1.vue
  frontend/src/views/Componentes2.vue
  frontend/src/views/DevelopmentScreen.vue
  frontend/src/views/HomeView.vue
  frontend/tsconfig.app.json
Labels: Task, frontend, Review effort 1/5

#207 Refactor frontend app to use layouts
  frontend/src/router.ts
  frontend/src/views/AboutUs.vue
  frontend/src/views/Contact.vue
  frontend/src/views/HotelDetailView.vue
  frontend/src/views/HotelListScreen.vue
  frontend/src/views/HotelOwnerPanel.vue
  frontend/src/views/LayoutDefault.vue
  frontend/src/views/LayoutWithFilter.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/MyBookings.vue
  frontend/src/views/RegisterView.vue
  frontend/src/views/UserProfile.vue
Labels: Review effort 3/5

#203 Filtros hotel y roomType
  backend/pawtel/hotels/services.py
  backend/pawtel/hotels/tests/test_views3.py
  backend/pawtel/hotels/views.py
  backend/pawtel/permission_services.py
  backend/pawtel/room_types/services.py
Labels: test, backend, Review effort 3/5

#209 Añadir atributo a hotel_owner y metodo para cambiarlo de estado
  backend/pawtel/hotel_owners/migrations/0003_hotelowner_is_approved.py
  backend/pawtel/hotel_owners/models.py
  backend/pawtel/hotel_owners/serializers.py
  backend/pawtel/hotel_owners/services.py
  backend/pawtel/hotel_owners/tests/test_services.py
  backend/pawtel/hotel_owners/tests/test_views.py
  backend/pawtel/hotel_owners/views.py
  backend/pawtel/permission_services.py
Labels: Feature, backend, Review effort 3/5

#212 Add automatic route guarding
  frontend/src/router.ts
Labels: Review effort 3/5

#200 Pantalla Mis Reservas
  backend/pawtel/bookings/serializers.py
  backend/pawtel/customers/views.py
  backend/pawtel/management/commands/seed.py
  backend/pawtel/management/commands/seed_bookings.py
  backend/pawtel/room_types/views.py
  frontend/src/components/NavBarTerracota.vue
  frontend/src/data-layer/api/bookings.ts
  frontend/src/data-layer/api/customers.ts
  frontend/src/data-layer/api/hotels.ts
  frontend/src/data-layer/api/roomTypes.ts
  frontend/src/data-layer/hooks/bookings.ts
  frontend/src/data-layer/hooks/customers.ts
  frontend/src/data-layer/hooks/hotels.ts
  frontend/src/data-layer/hooks/roomTypes.ts
  frontend/src/router.ts
  frontend/src/views/EditHotel.vue
  frontend/src/views/HotelOwnerPanel.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/MisHoteles.vue
  frontend/src/views/MyBookings.vue
  frontend/src/views/TemplateScreen.vue
Labels: Review effort 3/5

#219 Arreglar filtro de hoteles y su autorización
  backend/pawtel/bookings/models.py
  backend/pawtel/hotels/services.py
  backend/pawtel/hotels/tests/test_views3.py
  backend/pawtel/hotels/views.py
  backend/pawtel/permission_services.py
  backend/pawtel/room_types/services.py
Labels: Review effort 3/5

#218 Refactorizar Login y Register
  frontend/src/views/LoginView.vue
  frontend/src/views/RegisterView.vue
Labels: Review effort 2/5

#222 Codacy WF to Main
  .github/workflows/codacy_report.yml
  .github/workflows/test.yml
Labels: Review effort 2/5

#208 Actualizacion queries Tan Stack nuevas urls
  frontend/src/data-layer/api/bookingholds.ts
  frontend/src/data-layer/api/bookings.ts
  frontend/src/data-layer/api/customers.ts
  frontend/src/data-layer/api/hotelImages.ts
  frontend/src/data-layer/api/hotels.ts
  frontend/src/data-layer/api/roomTypes.ts
  frontend/src/data-layer/hooks/bookingholds.ts
  frontend/src/data-layer/hooks/bookings.ts
  frontend/src/data-layer/hooks/hotelImages.ts
  frontend/src/data-layer/hooks/hotels.ts
  frontend/src/data-layer/hooks/roomTypes.ts
Labels: Review effort 3/5

#217 Actualizar covers de HotelImage
  backend/pawtel/hotels/serializers.py
  backend/pawtel/hotels/services.py
  backend/pawtel/hotels/tests/test_views.py
  backend/pawtel/hotels/views.py
  backend/pawtel/permission_services.py
Labels: Review effort 2/5

#226 Hotel Details Screen refactorización
  frontend/src/components/HotelDetailCard.vue
  frontend/src/router.ts
  frontend/src/views/HotelDetailView.vue
  frontend/src/views/LayoutDefaultWhite.vue
Labels: Review effort 2/5

#228 Refactor Hotel List & Filter Screen
  frontend/src/components/DatePicker.vue
  frontend/src/components/FilterNavBar.vue
  frontend/src/components/hotels/HotelFilters.vue
  frontend/src/components/hotels/HotelList.vue
  frontend/src/components/hotels/HotelMobileFilters.vue
  frontend/src/components/hotels/HotelMobileSorting.vue
  frontend/src/components/hotels/HotelSorting.vue
  frontend/src/components/hotels/PriceRange.vue
  frontend/src/data-layer/api/hotels.ts
  frontend/src/views/Home.vue
  frontend/src/views/HotelListScreen.vue
  frontend/src/views/LayoutTerracotaMargins.vue
  frontend/src/views/LayoutWithFilter.vue
  node_modules/.package-lock.json
  package-lock.json
  package.json
Labels: Review effort 3/5

#221 Implementada Pasarela de Pago
  backend/.env.example
  backend/pawtel/bookings/services.py
  backend/pawtel/bookings/views.py
  backend/pawtel/settings.py
  backend/requirements.txt
  frontend/src/components/HotelDetailCard.vue
  frontend/src/data-layer/api/bookings.ts
  frontend/src/data-layer/hooks/bookings.ts
  frontend/src/router.ts
  frontend/src/views/BookingReservationForm.vue
  frontend/src/views/ClientNotLoggedIn.vue
Labels: Review effort 4/5, Feature

#231 Pulir un poco el sistema de reservas/pagos
  backend/.env.example
  backend/pawtel/bookings/services.py
  backend/pawtel/settings.py
  frontend/src/components/Button.vue
  frontend/src/components/HotelDetailCard.vue
  frontend/src/data-layer/hooks/bookings.ts
  frontend/src/router.ts
  frontend/src/views/BookingReservationForm.vue
  frontend/src/views/ClientNotLoggedIn.vue
Labels: Review effort 3/5

#232 Aceptación Términos y Condiciones
  backend/pawtel/app_users/migrations/0002_termsacceptance.py
  backend/pawtel/app_users/models.py
  backend/pawtel/app_users/serializers.py
  backend/pawtel/app_users/services.py
  backend/pawtel/utils.py
  frontend/src/data-layer/api/customers.ts
  frontend/src/views/RegisterView.vue
Labels: Review effort 2/5

#227 Logica archivado y borrado
  backend/pawtel/app_users/services.py
  backend/pawtel/customers/services.py
  backend/pawtel/customers/views.py
  backend/pawtel/hotel_owners/services.py
  backend/pawtel/hotel_owners/tests/test_services2.py
  backend/pawtel/hotel_owners/views.py
  backend/pawtel/hotels/services.py
  backend/pawtel/hotels/views.py
  backend/pawtel/room_types/services.py
  backend/pawtel/room_types/views.py
Labels: test, backend, Review effort 3/5

#234 Rediseñar User Profile Provisional
  frontend/src/views/UserProfile.vue
Labels: Review effort 3/5

#233 Pantalla de habitaciones y precios
  frontend/src/router.ts
  frontend/src/views/HotelRoomsAndPrices.vue
Labels: Feature, frontend, Review effort 2/5

#235 Actualización de TimeEffortReport
  docs/Sprint_2/AIusage.md
  docs/Sprint_2/graficas/yesica.png
  docs/Sprint_2/timeEffortReport.md
Labels: documentation, Review effort 1/5

#248 Mejorar max y min price de hoteles
  backend/pawtel/hotels/serializers.py
  backend/pawtel/hotels/services.py
Labels: Review effort 2/5
